### ISSUE TITLE
Following Quickstart Guide - How to create a remote user?

### ISSUE THREAD

**Issue by laboro18** [auth0-samples/auth0-django-api#19]
Hi all, I'm following the [quickstart guide](https://auth0.com/docs/quickstart/backend/django#add-a-django-remote-user). 

I'm stuck on the final step `Then create a remote user in Django authentication system. Please check the Django documentation for more information. `
I have read the linked docs, however its about authentication using REMOTE_USER and does not elaborate on how to actually create a remote user.

So how do I go about creating a remote user? Any help will be appreciated :)

**Comment by MitchSRobinson** [comment]
Hi there,

I think I'm stuck in the same problem as you were - did you manage to find a solution? 

Currently the only response I get is "Incorrect authentication credentials." so could really do with some assistance.

Thanks

**Comment by xcdr** [comment]
Hi,

I have the same problem,  I get is "Incorrect authentication credentials." and don't know how to create valid django user (I created user with the same login and e-mail).

**Comment by zrev2220** [comment]
Has anyone figured out a solution?

I'm confused on this step too. The Auth0 docs and the Django docs are not clear as to whether I simply create a normal Django user and mentally declare it the "remote user," or if there's some other special procedure to follow.

**Comment by seanwhudson** [comment]
It's not super clear anywhere, but it becomes clearer if you change the code to this:

```
from django.contrib.auth import authenticate

def jwt_get_username_from_payload_handler(payload):
  username = payload.get('sub').replace('|', '.')
  user = authenticate(remote_user=username)
  print('user', user, payload)
  return username
```

Django has actually created a User that has no password where the username comes from the auth0 normalized dataset. If you do a search in Users table on the username that is returned you'll find a blank User object! You can then modify the User however you need.
