### ISSUE TITLE
Always returns incorrect authentication details

### ISSUE THREAD

**Issue by MishY111** [auth0-samples/auth0-django-api#2]
Downloaded project to test received: {"detail":"Incorrect authentication credentials."}

Tried in my own project. Same result.

**Comment by aaguiarz** [comment]
Hi,

Can you provide details of how are you calling the API?

Thanks

**Comment by MishY111** [comment]
Hi

Followed the tutorial. Using the key from my account with rs256. I also get invalid signature. The access token is from the test client.

API url is http://127.0.0.1:8000/api as still in dev.

Have put access token and key into jwt.io and looks good.

If that’s not enough info will update tomorrow when have access to code.

**Comment by MishY111** [comment]
And testing with postman http://127.0.0.1:8000/private get request with bearer as access token

**Comment by MishY111** [comment]
certificate_text = open("rsa_certificates/XXX.pem", 'rb').read()
certificate = load_pem_x509_certificate(certificate_text, default_backend())
default_publickey = certificate.public_key()

JWT_AUTH = {
    'JWT_PUBLIC_KEY': default_publickey,
    'JWT_ALGORITHM': 'RS256',
    'JWT_AUDIENCE': 'http://127.0.0.1:8000/api/',
    'JWT_ISSUER': 'https://XXX.eu.auth0.com/',
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
}

Get the same problem using urlopen as per tutorial.

**Comment by MishY111** [comment]
The issue is line 59 restframework_jwt/authentication.py

user = User.objects.get_by_natural_key(username)

Because when you create a user in Django Admin it doesn't exist on Auth0 or vice versa, no users are found using the above query. Forcing it by getting a pk makes it work fine.

**Comment by MishY111** [comment]
Can I suggest the tutorial is rewritten to use https://github.com/mcueto/djangorestframework-auth0

**Comment by vaibhavmule** [comment]
@MishY111 

I got the same issue with my setup.

I have tried it :  https://github.com/mcueto/djangorestframework-auth0 , does it worked for you?

**Comment by alexisluque** [comment]
Hi

To solve this issue you should modify the function `jwt_get_username_from_payload_handler` with the following:

```python
def jwt_get_username_from_payload_handler(payload):
    return payload.get('sub').replace('|', '.')
```

And create a user in Django admin with `user_id` from Auth0's user profile as username.
