### ISSUE TITLE
djangorestframework-jwt seems abandoned

### ISSUE THREAD

**Issue by bdesbiolles** [auth0-samples/auth0-django-api#21]
This tutorial is using [django-rest-framework-jwt](https://github.com/GetBlimp/django-rest-framework-jwt) which seems to be abandoned. 

The Django REST Framework website have been updated its documentation following this issue: https://github.com/encode/django-rest-framework/pull/6138 and recommend using [django-rest-framework-simplejwt](https://github.com/davesque/django-rest-framework-simplejwt)

**Comment by dmwyatt** [comment]
>  If you have not received a response for our team (apologies for the delay) and this is still a blocker, please reply with additional information or just a ping

It's not clear what "blocker" means exactly when it comes to docs, but this issue is still an...an issue.
