### ISSUE TITLE
auth0 Django API tutorial relies on unmaintained djangorestframework-jwt

### ISSUE THREAD

**Issue by jrsmartyn** [auth0-samples/auth0-django-api#28]
Issue #21 was marked as stale and closed due to a lack of comment. Since then, there has been a discussion on github from the maintainer on the use of djangorestframework-jwt. See the [Github](https://github.com/jpadilla/django-rest-framework-jwt) page and specifically [issue #484](https://github.com/jpadilla/django-rest-framework-jwt/issues/484) for details.

The [maintainer](https://github.com/jpadilla/django-rest-framework-jwt/issues/484) **and** [Django now recommend](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) the use of [SimpleJWT](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/) instead of the now unmaintained (and _last committed to in 2017_) drf-jwt.

All Django-based tutorials from auth0 (including this one) rely on the currently unmaintained drf-jwt.  As this is used in the final step of authentication, it leaves those who follow these tutorials open to security issues.

There has been further [discussion of this issue in the auth0 community](https://community.auth0.com/t/use-with-simplejwt/34226) from back in Nov, 2019. However, this discussion has since been marked as closed.  There is a mention from one user in the thread who seems to have successfully implemented SimpleJWT, but no link to his solution.  

I have followed his idea of modifying drf-simplejwt's source code with an auth0decode method that follows the methods used with drf-jwt in the auth0 Django API tutorial (see [jwt_decode_token(token)](https://auth0.com/docs/quickstart/backend/django#validate-access-tokens)).  Specifically, modifying the backends.py with this method and then calling it in the constructor function of the Token class in tokens.py, successfully passes the token with simpleJWT. However, I have been unable to figure out how to perform the server authentication step, as is done with the settings.py (and utils.py) files in this tutorial (relying on the unmaintained drf-jwt package, with settings given by JWT_AUTH):
```
def jwt_get_username_from_payload_handler(payload):
    username = payload.get('sub').replace('|', '.')
    authenticate(remote_user=username)
    return username

JWT_AUTH = {
   'JWT_PAYLOAD_GET_USERNAME_HANDLER':
       jwt_get_username_from_payload_handler,
       [...]

}
```
I'll re-open this as an outstanding issue with this tutorial in hopes that it may be prioritized for your team.  If anyone has a workable solution for implementing SimpleJWT, please comment!

For further review, here are 2 other relevant discussions hosted on the SimpleJWT github page:
[User ID Method Handling (#169)](https://github.com/SimpleJWT/django-rest-framework-simplejwt/issues/169)
[Verifying audience and issuer claims (#38)](https://github.com/SimpleJWT/django-rest-framework-simplejwt/issues/38)

**Comment by naquiroz** [comment]
Hi, I'm looking into this, but I haven't found any proper solution. Did you manage to implement auth0 using this library?

**Comment by andylamp** [comment]
why is this issue closed...? As far as I understand this has not been resolved...
