### ISSUE TITLE
TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by vaibhavmule** [auth0-samples/auth0-django-api#4]
`certificate = load_pem_x509_certificate(str.encode(cert), default_backend()) `

Python 2.7.13
Mac OS Sierra

**Comment by alexisluque** [comment]
Hi,
You should change this:
`certificate = load_pem_x509_certificate(str.encode(cert), default_backend())`
for this one:
`certificate = load_pem_x509_certificate(cert.encode('utf-8'), default_backend())`

**Comment by vaibhavmule** [comment]
so this one also works with Python 3?

`certificate = load_pem_x509_certificate(cert.encode('utf-8'), default_backend())
`

**Comment by alexisluque** [comment]
Yes, it should work on python 3.
