### ISSUE TITLE
rest_framework_jwt no longer maintained

### ISSUE THREAD

**Issue by tomboolean** [auth0-samples/auth0-django-api#50]
https://stackoverflow.com/questions/72102911/could-not-import-rest-framework-jwt-authentication-jsonwebtokenauthentication

1. The following should be updated:

# apiexample/settings.py

```
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}
```

2. Update the requirements.txt as well to reflect using the simplejwt dependencies as well.

**Comment by evansims** [comment]
Hi @tomboolean, thanks for your suggestion. A reworked sample is already being prepared that resolves this. You can review it at https://github.com/auth0-samples/auth0-django-api/tree/py-vnext
